/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-02-15 11:21:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fui_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String string = (String) request.getAttribute("msg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>User Input Validation</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #6a9ac4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contact {\r\n");
      out.write("	background-color: #6a9ac4;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-box {\r\n");
      out.write("	width: clamp(100px, 90%, 1000px);\r\n");
      out.write("	margin: 80px 50px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* for message and button design */\r\n");
      out.write(".contact-links, .contact-form-wrapper {\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	padding: 8% 5% 10% 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* for enter hear back ground design */\r\n");
      out.write(".contact-links {\r\n");
      out.write("	background-color: #1f2e43;\r\n");
      out.write("	background: radial-gradient(circle at 55% 92%, #426691 0 12%, transparent 12.2%),\r\n");
      out.write("		radial-gradient(circle at 94% 72%, #426691 0 10%, transparent 10.2%),\r\n");
      out.write("		radial-gradient(circle at 20% max(78%, 350px), #263a53 0 7%,\r\n");
      out.write("		transparent 7.2%),\r\n");
      out.write("		radial-gradient(circle at 0% 0%, #263a53 0 40%, transparent 40.2%),\r\n");
      out.write("		#1f2e43;\r\n");
      out.write("	border-radius: 10px 0 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* input field back ground design */\r\n");
      out.write(".contact-form-wrapper {\r\n");
      out.write("	background-color: #ffffff8f;\r\n");
      out.write("	border-radius: 0 10px 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* for enter hear text h2 heading */\r\n");
      out.write("h2 {\r\n");
      out.write("	font-family: 'Arimo', sans-serif;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-size: clamp(30px, 6vw, 60px);\r\n");
      out.write("	letter-spacing: 2px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	transform: scale(.95, 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-item {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*   for font style all ui */\r\n");
      out.write("label, input, textarea {\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* for message text alignment in input field */\r\n");
      out.write("label {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 10px;\r\n");
      out.write("	left: 2%;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	font-size: clamp(14px, 1.5vw, 18px);\r\n");
      out.write("	pointer-events: none;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* for message Box */\r\n");
      out.write("input, textarea {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	outline: 0;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	font-size: clamp(15px, 1.5vw, 18px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit-btn:hover {\r\n");
      out.write("	transform: scale(1.1, 1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit-btn:active {\r\n");
      out.write("	transform: scale(1.1, 1.1);\r\n");
      out.write("	filter: sepia(0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  Message text in user input */\r\n");
      out.write("input:focus+label, input:valid+label, textarea:focus+label, textarea:valid+label\r\n");
      out.write("	{\r\n");
      out.write("	font-size: clamp(13px, 1.3vw, 16px);\r\n");
      out.write("	color: #777;\r\n");
      out.write("	top: -20px;\r\n");
      out.write("	transition: all .225s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  For Button Style */\r\n");
      out.write(".submit-btn {\r\n");
      out.write("	background-color: #fd917e;\r\n");
      out.write("	filter: drop-shadow(2px 2px 3px #0003);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-family: \"Poppins\", sans-serif;\r\n");
      out.write("	font-size: clamp(16px, 1.6vw, 18px);\r\n");
      out.write("	display: block;\r\n");
      out.write("	padding: 12px 20px;\r\n");
      out.write("	margin: 2px auto;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("	transition: 0.2s;\r\n");
      out.write("	'\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cent {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 40px;\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-shadow: -5px 5px 2px #546E7A;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	if (string != null && !string.isEmpty()) {
	
      out.write("\r\n");
      out.write("	<marquee behavior=\"scroll\" direction=\"up\" scrollamount=\"4\">\r\n");
      out.write("		<h3 class=\"cent\">");
      out.print(string);
      out.write("</h3>\r\n");
      out.write("	</marquee>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("	<section id=\"contact\">\r\n");
      out.write("		<div class=\"contact-box\">\r\n");
      out.write("			<div class=\"contact-links\">\r\n");
      out.write("				<h2>Enter Here</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"contact-form-wrapper\">\r\n");
      out.write("				<form action=\"/user_input_validation/User\" method=\"post\">\r\n");
      out.write("					<div class=\"form-item\">\r\n");
      out.write("						<textarea class=\"\" name=\"data\" required></textarea>\r\n");
      out.write("						<label>Message:</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button class=\"submit-btn\">Send</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
